### ISSUE TITLE
autogen.sh failing

### ISSUE THREAD

**Issue by Qambar** [watsonbox/homebrew-cmu-sphinx#2]
I am using OS X 10.10.1 Yosemite

$ brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxbase
==> Installing cmu-sphinxbase from watsonbox/homebrew-cmu-sphinx
==> Cloning https://github.com/cmusphinx/sphinxbase.git
Updating /Library/Caches/Homebrew/cmu-sphinxbase--git
==> Checking out branch master
==> ./autogen.sh
configure.in:56: error: possibly undefined macro: AM_CONDITIONAL
configure.in:199: error: possibly undefined macro: AM_PATH_PYTHON
Running ./configure ...
./configure: line 2366: syntax error near unexpected token `no-define'
./configure: line 2366:`AM_INIT_AUTOMAKE(no-define foreign)'

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/watsonbox/homebrew-cmu-sphinx/issues

**Comment by rouxpz** [comment]
just ran into this issue while installing, but the fix provided by @Qambar seems to be working fine for me. wanted to let you know, thanks!
