### ISSUE TITLE
Error using sphinxtrain - Failed to find sphinxtrain binaries. Check your installation

### ISSUE THREAD

**Issue by mrwaim** [watsonbox/homebrew-cmu-sphinx#3]
Hi,

When I run sphinxtrain -t mydb setup - i get

Failed to find sphinxtrain binaries. Check your installation

The workaround, is to
 cd /usr/local/Cellar/cmu-sphinxtrain/HEAD/bin/etc
 ./sphinxtrain -t mydb setup

Output looks like
Bellevue-MacBook:bin ibrar$ ./sphinxtrain -t aliklas setup
Sphinxtrain path: /usr/local/Cellar/cmu-sphinxtrain/HEAD/lib/sphinxtrain
Sphinxtrain binaries path: /usr/local/Cellar/cmu-sphinxtrain/HEAD/libexec/sphinxtrain
Setting up the database mydb

You can see from here - that it is looking for bw
http://sourceforge.net/p/cmusphinx/mailman/message/31966059/

+if not os.path.exists(sphinxbinpath + "/bw"):
+    print "Failed to find sphinxtrain binaries. Check your installation"
+    exit(1)

bw is here - /usr/local/Cellar/cmu-sphinxtrain/HEAD/libexec/sphinxtrain/bw

I'm still new to unix/mac os so I'm not sure what exactly needs to be done to fix this. It seems like its missing a hardlink to libexec

**Comment by watsonbox** [comment]
Thanks, looks like this will require a small change to sphinxtrain.  I've submitted a pull request.

**Comment by watsonbox** [comment]
The fix has been merged into sphinxtrain through subversion.  Re-install and it should work fine:

```bash
$ brew uninstall watsonbox/cmu-sphinx/cmu-sphinxtrain
$ brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxtrain
```

**Comment by mrwaim** [comment]
Thanks! That was quick! I saw your change - you just looked up the symlink
- cool!

**Comment by kunalSinghGusain** [comment]
i'm having the same problem with sphinxtrain binaries on windows when i run the following command
    python ../sphinxtrain/scripts/sphinxtrain -t ayour_db setup
please help me.I'm working on a project and i have deadline. My file structure looks like this

acoustic
-your_db
-sphinxtrain
-sphinxbase
-pocketsphinx

**Comment by nuguse** [comment]
i'm having the same problem with sphinxtrain binaries on windows when i run the following command
python ../sphinxtrain/scripts/sphinxtrain -t other setup
please help me.I'm working on a project and i have deadline. My file structure looks like this

acoustic
-other
-sphinxtrain
-sphinxbase
-pocketsphinx
