### ISSUE TITLE
'SphinxBase was not found on your system.' when installing cmu-sphinxtrain or cmu-pocketsphinx

### ISSUE THREAD

**Issue by moonhouse** [watsonbox/homebrew-cmu-sphinx#4]
When following instructions in README.md I get the following on MacOS X 10.10.3 (after doing the "brew tap", "brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxbase" and then "brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxtrain"):

```
checking sphinx_config.h presence... no
checking for sphinx_config.h... no
configure: error: in `/private/tmp/cmu-sphinxtrain20150502-95862-ptyes0':
configure: error: SphinxBase was not found on your system.
See `config.log' for more details
couldn't understand kern.osversion `14.3.0'
```

Full [log here](https://gist.github.com/moonhouse/c928d5c074c140a3bce8).
[config.log](https://gist.github.com/moonhouse/d21bcb5f26d67b6f12ab)

This also happens for "brew install --HEAD watsonbox/cmu-sphinx/cmu-pocketsphinx".

```
==> Checking out branch master
==> ./autogen.sh
checking sphinx_config.h presence... no
checking for sphinx_config.h... no
configure: error: in `/private/tmp/cmu-pocketsphinx20150502-97638-8ex6ym':
configure: error: SphinxBase was not found on your system.
See `config.log' for more details
couldn't understand kern.osversion `14.3.0'
```

**Comment by watsonbox** [comment]
Hi thanks for this detailed info.  Could you possibly give me the output of `brew --config` on your system?
