### ISSUE TITLE
python libraries not installing on 10.10 yosemite

### ISSUE THREAD

**Issue by rouxpz** [watsonbox/homebrew-cmu-sphinx#5]
this version was working well for me on 10.9.5 but i recently had to install on a machine running 10.10.3, and the python libraries do not install. i fixed this by manually moving over the relevant files from my mavericks machine, but wanted to alert you to this ASAP.

thanks!

**Comment by watsonbox** [comment]
Thanks for flagging this up.  Please see my own [install log](https://github.com/watsonbox/homebrew-cmu-sphinx/wiki/Yosemite-10.10.3-Install-Log) for Yosemite 10.3.3.  There are some warning methods regarding python modules: is this the issue you refer to?  Does the fix suggested in the install log work?

**Comment by watsonbox** [comment]
Closing this.  Let me know if you still have problems which you believe are related to this tap.
