### ISSUE TITLE
compatible with jasper?

### ISSUE THREAD

**Issue by jskye** [watsonbox/homebrew-cmu-sphinx#6]
can i use this library with jasper (http://jasperproject.github.io/documentation/installation/#installing-sphinx)? It uses CMUCLMTK and  Phonetisaurus FST (openfst), m2m-aligner and MITLM but its doesnt detail a osx installation. i am wondering if the normal brew branch will be enough. but i want to have the real time recognition too.

**Comment by watsonbox** [comment]
Yes, you can.  Making Jasper installation easier on OSX was one of the reasons I created it:

https://github.com/jasperproject/jasper-client/issues/35#issuecomment-58926961

The normal brew recipe does not support microphone recognition on OSX as described in the [README](https://github.com/watsonbox/homebrew-cmu-sphinx/blob/master/README.md).
